baseURL = "http://tanksley.me/blog/"
languageCode = "en-us"
title = "Charlie Tanksley's Blog"
theme = "contrast-hugo"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"

[taxonomies]
    category = "categories"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "https://tanksley.me"
    weight = -110

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = -120

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
